kind: pipeline
name: amd64

platform:
  arch: amd64

steps:
- name: build
  image: busybox
  commands:
  - echo -n "$DRONE_COMMIT" > .tags
- name: deploy
  image: plugins/docker
  settings:
    repo: charlieegan3/music
    username: charlieegan3
    password:
      from_secret: DOCKER_PASSWORD

---
kind: pipeline
type: docker
name: arm

platform:
  arch: arm

steps:
- name: build
  image: busybox
  commands:
  - echo -n "$DRONE_COMMIT" > .tags
- name: deploy
  image: plugins/docker
  settings:
    repo: charlieegan3/music
    username: charlieegan3
    password:
      from_secret: DOCKER_PASSWORD
