name: Build Site

on:
  schedule:
  - cron: '0 5 * * *'

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push site to netlify branch
      run: |
        cd website

        ruby ./bin/generate.rb
