name: Build Binary

on:
  release:
    types:
    - published

jobs:
  refresh:
    name: build-binary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make binary

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: music
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
