name: build-site

on:
  push:
    branches: [ master ]
    paths:
    - 'website/**'
  schedule:
  - cron: '0 5 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push site to netlify branch
      run: |
        cd website

        ruby ./bin/generate.rb
