name: build-site

on:
  push:
    branches: [ master ]
  schedule:
  - cron: '* 5 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Repo Readme
      run: |

        cd website

        ruby ./bin/generate.rb
