name: Sync Spotify

on:
  schedule:
  - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  sync:
    name: Sync Spotify
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download binary
      uses: charlieegan3/fetch-gh-release-asset@master
      with:
        file: "music"
        target: "/usr/local/bin/music"
        chmod_x: true

    - name: Run
      env:
        CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
      run: |
        echo $CONFIG_FILE | base64 -d > config.yaml

        music sync spotify
