name: sync-spotify

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  refresh:
    name: run
    runs-on: ubuntu-latest
    steps:

    - name: Download Image
      uses: nick-invision/retry@v1
      with:
        timeout_minutes: 3
        max_attempts: 5
        command: docker pull charlieegan3/music:latest

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run
      env:
        CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
      run: |
        echo $CONFIG_FILE | base64 -d > config.yaml

        docker run -v $(pwd)/config.yaml:/config.yaml charlieegan3/music:latest sync spotify
